In [4]:
import numpy
import random
from scipy.optimize import minimize


EPS = 1e-12

def likelihood(thetas: tuple[int, int], input: numpy.ndarray | list):
    mapping = {
        (0, 0): thetas[0], 
        (0, 1): 1 - thetas[0],
        (1, 1): thetas[1], 
        (1, 0): 1 - thetas[1]
    }

    neg_log_lik = 0 

    for i in range(len(input)-1):
        neg_log_lik -= numpy.log(mapping[(input[i], input[i+1])] + EPS)
    
    return neg_log_lik


input = numpy.loadtxt("Input.txt")

theta_0 = [0.5, 0.5]
bounds = ((0, 1), (0, 1))

observed_mle = minimize(fun=lambda thetas: likelihood(thetas, input), x0 = theta_0, bounds = bounds).x

random.seed(3)

resampled = random.choices(input, k=len(input))
check_resampling = numpy.loadtxt("Exc7Task1_BootstrapSample1.txt")
assert numpy.array_equal(resampled, check_resampling)

resampled_theta_0 = [0.2, 0.2]
resampled_mle = minimize(fun=lambda thetas: likelihood(thetas, resampled), x0 = theta_0, bounds = bounds).x



In [5]:
observed_mle

array([0.57142863, 0.75      ])

In [6]:
resampled_mle

array([0.37499997, 0.59090906])

In [18]:
random.choices([0,1], weights=[0.4,0.6], k = 18)

[0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0]

In [15]:
n_1 = sum(input)
n_1

np.float64(25.0)

In [17]:
n_0 = len(input) -n_1
n_0

np.float64(14.0)

In [20]:
resampled_mle

array([0.66666668, 0.42856982])